#!/usr/bin/env python

from sys import argv

from pickle import dumps

from markovdrummer.midi import clean, quantize, track2beats, beats2table, writetables
from markovdrummer.markov import analyze, generate

import midi

if __name__ == '__main__':

	filename = argv[ 1 ].split( '.' )[ 0 ]
	quantize_resoluzion = int( argv[ 2 ] )
	memory = int( argv[ 3 ] )

	original = midi.read_midifile( filename + '.mid' )

	track = clean( original[ 1 ] if original.format == 1 else original[ 0 ] )
	quantize_resoluzion = original.resolution / quantize_resoluzion
	qtrack = quantize( track, quantize_resoluzion )
	beats = track2beats( qtrack, quantize_resoluzion )
	model = analyze( beats, memory )

	print model
	with open( filename + '.model', 'w' ) as f: f.write( dumps( model ) )

	writetables( [ beats2table( beats ) ], filename + '.html' )

	qmidi = midi.Pattern(
		format = original.format,
		resolution = original.resolution,
		tracks =  [ original[ 0 ], qtrack ] if original.format == 1 else [ qtrack ]
	)
	midi.write_midifile( filename + '-q.mid', qmidi )

