#!/usr/bin/env python

from sys import argv

import midi

from markovdrummer import filebaseext
from markovdrummer.markov import analyze, save
from markovdrummer.midi import track2beats

if __name__ == '__main__':

	filename = argv[ 1 ]
	basename, _ = splitext( basename( filename ) )
	tick_per_quantum = int( argv[ 2 ] )
	memory = int( argv[ 3 ] )

	original = midi.read_midifile( filename )

	beats = track2beats( original[ 0 ], tick_per_quantum )
	model = analyze( beats, memory )

	save( model, '{}.t{}-m{}.model'.format( basename, tick_per_quantum, memory ) )

