#!/usr/bin/env python

from sys import argv

import midi

from markovdrummer import filebaseext
from markovdrummer.markov import load
from markovdrummer.midi import quantize, track2beats, beats2table, model2tables, writetables

if __name__ == '__main__':

	filename, basename, ext = filebaseext( argv[ 1 ] )

	if ext == '.mid':
		original = midi.read_midifile( filename )
		track = original[ 0 ] if original.format == 0 else original[ 1 ]
		qstats, _ = quantize( track )
		tick_per_quantum = min( qstats )[ 0 ]
		print 'tick_per_quantum = {} '.format( tick_per_quantum )
		writetables( [ beats2table( track2beats( track, tick_per_quantum ) ) ], basename + ext + '.html' )
	elif ext == '.model':
		model = load( filename )
		writetables( model2tables( model ), basename + ext + '.html' )
