#!/usr/bin/env python

from sys import argv

from markovdrummer import filebaseext
from markovdrummer.markov import load, save

if __name__ == '__main__':
	merged = dict()
	basenames = []
	for filename in argv[ 1 : ]:
		filename, basename, _ = filebaseext( filename )
		basenames.append( basename )
		model = load( filename )
		for k, v in model.items():
			merged.setdefault( k, [] ).extend( v )
	save( merged, '-'.join( basenames ) + '.model' )
