#!/usr/bin/env python

from sys import argv

import midi

from markovdrummer import filebaseext
from markovdrummer.midi import quantize

if __name__ == '__main__':

	filename, basename, _ = filebaseext( argv[ 1 ] )
 	tick_per_quantum = int( argv[ 2 ] )

	original = midi.read_midifile( filename )
	qstats, qtrack = quantize( original[ 0 ], tick_per_quantum )

	midi.write_midifile( '{}.q{}.mid'.format( basename, tick_per_quantum ), midi.Pattern( format = 0, resolution = original.resolution, tracks = [ qtrack ] ) )

	print 'qstats:'
	for delta, count in qstats:
		print '\ttick {}: # {}'.format( delta, count )
