#!/usr/bin/env python

from sys import argv

import midi

from markovdrummer.midi import quantize, trackstats, pitch2part

if __name__ == '__main__':

	filename = argv[ 1 ]

	original = midi.read_midifile( filename )

	print 'format: {}\nresolution: {}'.format( original.format, original.resolution )

	for n, track in enumerate( original ):

		qstats, _ = quantize( track )
		print 'track #{} qstats:'.format( n )
		for delta, count in qstats:
			print '\ttick {}: # {}'.format( delta, count )

		print 'track #{} pitches:'.format( n )
		for pitch, count in trackstats( track ):
			print '\tpitch {}: # {}'.format( pitch2part( pitch ), count )
